class RetryException(Exception):
    pass

class arrowError(Exception):
    pass